version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend:/usr/src/app/  # ホストマシンのfrontendディレクトリをコンテナの/usr/src/app/frontendにマウント
      - /usr/src/app/node_modules