version: '3'

services:
  db:
    # build: .でdocker-compose.ymlと同じフォルダにDockerfileがあることを示す
    build: 
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
volumes:
  db-store: