version: '3'

services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - 80:80
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ./backend/laravel:/var/www/html
      - ./docker/apache/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - net1
  react:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - net1
    volumes:
      - ./frontend/react:/usr/src/app/  # ホストマシンのfrontendディレクトリをコンテナの/usr/src/app/frontendにマウント
      - /usr/src/app/node_modules
  db:
    container_name: db_01
    restart: always
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_balancer_local
    networks:
      - net1
    ports:
      - 5432:5432
networks:
  net1: